// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: editor.proto

package editorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EditorClient is the client API for Editor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EditorClient interface {
	Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error)
}

type editorClient struct {
	cc grpc.ClientConnInterface
}

func NewEditorClient(cc grpc.ClientConnInterface) EditorClient {
	return &editorClient{cc}
}

func (c *editorClient) Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error) {
	out := new(DoResponse)
	err := c.cc.Invoke(ctx, "/Editor/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EditorServer is the server API for Editor service.
// All implementations must embed UnimplementedEditorServer
// for forward compatibility
type EditorServer interface {
	Do(context.Context, *DoRequest) (*DoResponse, error)
	mustEmbedUnimplementedEditorServer()
}

// UnimplementedEditorServer must be embedded to have forward compatible implementations.
type UnimplementedEditorServer struct {
}

func (UnimplementedEditorServer) Do(context.Context, *DoRequest) (*DoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedEditorServer) mustEmbedUnimplementedEditorServer() {}

// UnsafeEditorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EditorServer will
// result in compilation errors.
type UnsafeEditorServer interface {
	mustEmbedUnimplementedEditorServer()
}

func RegisterEditorServer(s grpc.ServiceRegistrar, srv EditorServer) {
	s.RegisterService(&Editor_ServiceDesc, srv)
}

func _Editor_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Editor/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Do(ctx, req.(*DoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Editor_ServiceDesc is the grpc.ServiceDesc for Editor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Editor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Editor",
	HandlerType: (*EditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Editor_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "editor.proto",
}
